export const NaveITems = [
  {
    id: 'dashboard',
    title: 'داشبورد',
    toolTip: '',
    icon: 'pi pi-apple',
    isShow: true,
    order: 1,
    parentId: null,
  },
  {
    id: 'bassInfo',
    title: 'اطلاعات پایه',
    toolTip: '',
    icon: 'pi pi-android',
    isShow: true,
    order: 2,
    children: [],
    parentId: null,
  },
  {
    id: 'dashboard1',
    title: '1داشبورد',
    url:"pages/dashboard",
    toolTip: '',
    icon: '',
    isShow: true,
    order: 3,
    parentId: 'dashboard',
  },
  {
    id: 'dashboard2',
    title: '2داشبورد',
    toolTip: '',
    icon: '',
    isShow: true,
    order: 4,
    parentId: 'dashboard',
  },
];
